### ISSUE TITLE
无法添加用户

### ISSUE THREAD

**Issue by Aar0nJaw** [hellofwy/ss-bash#10]
每当尝试添加/删除用户都提醒 ：ss-bash/ssadmin.sh: line 269: kill: (20272) - No such process
我是使用的config启动是shadowsocks不知是否影响（ssserver -c /etc/shadowsocks.json -d start）
pip安装的shadowsocks，不知道是否还需要更改路径否
每次添加新用户需要重新启动ss bash吗

**Comment by hellofwy** [comment]
-d 参数会fork个新进程出来，所以加了-d参数要改其他的部分：
请参考：
#6

**Comment by Aar0nJaw** [comment]
@hellofwy 我修改成$SSSERVER -c $JSON_FILE -d start直接ssserver启动失败

**Comment by xuexingmali** [comment]
@Aar0nJaw
显然你没在sslib.sh里指定ssserver路径。

**Comment by Aar0nJaw** [comment]
@xuexingmail 已经修改过了。默认pip安装的
