### ISSUE TITLE
有时会出现Ds 0:24 [ssserver]

### ISSUE THREAD

**Issue by xuexingmali** [hellofwy/ss-bash#13]
你好，请问下Ds 0:24 [ssserver]什么情况。
有时会连不上，然后./ssadmin.sh status后就会显示pid Ds 0:24 [ssserver]，正常情况是显示ssserver的启动命令，如果把ssserver kill掉显示的是ssserver未启动。

**Comment by hellofwy** [comment]
从这些信息我也无法判断是什么问题。

有时连不上，也有可能是网络问题，不是服务器的问题。

最好不要自己kill掉ssserver，因为通过ssadmin.sh启动时会将pid保存到tmp/下的pid文件中，kill命令并不会自动删除对应文件夹下的pid文件。

尝试运行ssadmin.sh restart，看看重启后是否正常。

**Comment by xuexingmali** [comment]
@hellofwy
谢谢你的回复。
每当我连不上时登录后看./ssadmin.sh status都显示Ds 0:xx [ssserver],此时./ssadmin.sh restart后会恢复正常。这种情况每月只出现1-2次。看来我还是写个脚本来重启它吧。

**Comment by hellofwy** [comment]
又看了下man ps：
D 代表 uninterruptible sleep (usually IO)

按我理解，ssserver不应该出现这状态啊，如果有log输出到文件，那可能会有硬盘IO。
但ss-bash默认情况下运行ssserver的时候不会输出log。

你可以看看是不是ss版本问题，还是和其他同时安装的ss有冲突，还是设置的log输出的地方有问题。

**Comment by xuexingmali** [comment]
我开启的日志记录…

又看了下man ps：
D 代表 uninterruptible sleep (usually IO)

按我理解，ssserver不应该出现这状态啊，如果有log输出到文件，那可能会有硬盘IO。
但ss-bash默认情况下运行ssserver的时候不会输出log。

你可以看看是不是ss版本问题，还是和其他同时安装的ss有冲突，还是设置的log输出的地方有问题。

—
Reply to this email directly or view it on GitHub
<https://github.com/hellofwy/ss-bash/issues/13#issuecomment-184545034>.

**Comment by smileat** [comment]
@xxmali 你好，我也是遇见这样的问题，每个月总会有1-2次，ssserver会停止，用./ssadmin.sh status检查，就是显示 ssserver未启动，而sscounter.sh正在运行，你是怎么解决的呀？

**Comment by xxmali** [comment]
@smileat 你的情况和我的并不一样。你的应该是低内存进程被kill。
