### ISSUE TITLE
抱歉，问一个很蠢的问题。这个脚本怎么安装？

### ISSUE THREAD

**Issue by CraxGrix** [hellofwy/ss-bash#14]
解压出来后是一些.sh文件，用谷歌查了很多方法。发现都不行，用你那个新建用户的方法会报错：
-bash: sudo: command not found

**Comment by panxue** [comment]
https://github.com/hellofwy/ss-bash/wiki

**Comment by hellofwy** [comment]
可能是sudo命令没安装，先安装配置下sudo吧
同时再安装下awk和bc

**Comment by CraxGrix** [comment]
首先我wget软件下来，然后解压tar.gz。然后进入解压出来的目录。输入sudo ssadmin.sh add 8388 passed 10G 这些命令的话会提示 -bash: ssadmin.sh: command not found ss-bash应该是目录吧，我如果CD进去就不用填了对吧？ 谢谢

via CloudMagic for Mac
[https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.6.19&pv=10.11.3&source=email_footer_2]
On Tue, Mar 15, 2016 at 10:30 AM, 潘学 <notifications@github.com> wrote:
https://github.com/hellofwy/ss-bash/wiki
[https://github.com/hellofwy/ss-bash/wiki]

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/hellofwy/ss-bash/issues/14#issuecomment-196620499
[https://github.com/hellofwy/ss-bash/issues/14#issuecomment-196620499][https://github.com/notifications/beacon/APbLhU0l4Rul2VzY9WJvR8kf97YCv8HBks5pthmugaJpZM4Hwp57.gif]

**Comment by hellofwy** [comment]
sudo ./ssadmin.sh 试试

**Comment by CraxGrix** [comment]
因为我的debian是早上才装的，可能有些东西漏装了。所以我先安装一下sudo。

via CloudMagic for Mac
[https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.6.19&pv=10.11.3&source=email_footer_2]
On Tue, Mar 15, 2016 at 10:44 AM, hellofwy <notifications@github.com> wrote:
sudo ./ssadmin.sh 试试

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/hellofwy/ss-bash/issues/14#issuecomment-196625675
[https://github.com/hellofwy/ss-bash/issues/14#issuecomment-196625675][https://github.com/notifications/beacon/APbLhU-fv6mSjcKRH1kixEI4bJMQ9AnAks5pth0agaJpZM4Hwp57.gif]

**Comment by CraxGrix** [comment]
输入sudo ./ssadmin.sh的话会将sheep里面的内容显示出来
via CloudMagic for Mac
[https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.6.19&pv=10.11.3&source=email_footer_2]
On Tue, Mar 15, 2016 at 10:46 AM, jxh huang <huangjxh@gmail.com> wrote:
因为我的debian是早上才装的，可能有些东西漏装了。所以我先安装一下sudo。

via CloudMagic for Mac
[https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.6.19&pv=10.11.3&source=email_footer_2]
On Tue, Mar 15, 2016 at 10:44 AM, hellofwy <notifications@github.com> wrote:
sudo ./ssadmin.sh 试试

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/hellofwy/ss-bash/issues/14#issuecomment-196625675
[https://github.com/hellofwy/ss-bash/issues/14#issuecomment-196625675][https://github.com/notifications/beacon/APbLhU-fv6mSjcKRH1kixEI4bJMQ9AnAks5pth0agaJpZM4Hwp57.gif]

**Comment by hellofwy** [comment]
显示了什么内容？

**Comment by CraxGrix** [comment]
用法：
    显示版本：
        ssadmin.sh -v|v|version
    显示帮助：
        ssadmin.sh [-h|h|help]
    启动ss:
        ssadmin.sh start
    停止ss：
        ssadmin.sh stop
    查看ss状态：
        ssadmin.sh status
    重启ss：
        ssadmin.sh restart
    软重启ss：
        ssadmin.sh soft_restart
        在不影响现有连接的情况下重启ss服务。用于ss服务参数修改，
        和手动直接修改配置文件后，重启ss服务。
    添加用户：
        ssadmin.sh add port passwd limit
            port：端口号, 0<port<=65535
            passwd：密码, 不能有空格，引号等字符
            limit：流量限制，可以用K/M/G/T、KB/MB/GB/TB等（不区
                   分大小写）。支持小数。比如10.5G、10.5GB等。
                   1KB=1024 bytes，以此类推。
        示例： ssadmin.sh add 3333 abcde 10.5G
    显示用户流量信息：
        ssadmin.sh show port
    显示所有用户流量信息：
        ssadmin.sh show
    显示用户密码信息：
        ssadmin.sh showpw port
    显示所有用户密码信息：
        ssadmin.sh showpw
    删除用户：
        ssadmin.sh del port
    修改用户：
        ssadmin.sh change port passwd limit
    修改用户密码：
        ssadmin.sh cpw port passwd
    修改用户流量限制：
        ssadmin.sh clim port limit
    修改所有用户流量限制：
        ssadmin.sh change_all_limit limit
    用户流量使用量置零：
        ssadmin.sh rused limit
    所有用户流量使用量置零：
        ssadmin.sh reset_all_used
    用户流量限制置零：
        ssadmin.sh rlim port
    全部用户流量限制置零：
        ssadmin.sh reset_all_limit
    显示已添加的iptables规则：
        ssadmin.sh rules


显示了这些

**Comment by hellofwy** [comment]
哦，cd到ss-bash目录后，运行的时候需要变成 ./ssadmin.sh + 命令
之前是 ss-bash/ssadmin.sh + 命令

**Comment by panxue** [comment]
@CraxGrix 
-bash: ssadmin.sh: command not found ss-bash

感觉像 ssadmin.sh 没有执行权限
推荐运行 sudo chmod a+x ssadmin.sh

**Comment by CraxGrix** [comment]
./ssadmin.sh + 命令，这个方法是正确的。可是我start的时候，ssserver启动失败。因为我是新建一个json来当作ssserver 的启动配置文件，所以说路径也要指向这个配置文件吗？

**Comment by CraxGrix** [comment]
OK，使用which ssserver命令就可以找到ssserver文件的目录了。

**Comment by CraxGrix** [comment]
可是填写了文件目录后，启动还是会失败。不知道为什么。

**Comment by hellofwy** [comment]
这么配置：
https://github.com/hellofwy/ss-bash/wiki#%E8%87%AA%E5%AE%9A%E4%B9%89ssserver%E7%9A%84%E9%85%8D%E7%BD%AE

**Comment by CraxGrix** [comment]
问题解决了，谢谢！
