### ISSUE TITLE
密码中无法添加字符 $

### ISSUE THREAD

**Issue by KwToPA** [hellofwy/ss-bash#19]
密码为 XXXXX$zxczxc

```
sudo ss-bash/ssadmin.sh cpw 123 XXXXX
```

看vi ss-bash/ssmlt.json里
只有`XXXXX`后面一串$zxczxc都没了

**Comment by KwToPA** [comment]
本地SS修改密码为XXXXX可以正常使用，这是一个bug吗？

**Comment by jszh** [comment]
@KwToPA 因为 bash 中 $ 是变量名的标志，bash 会把它扩展成 $zxczxc 对应的变量值（空）。

**Comment by KwToPA** [comment]
您好，
感谢您的回复，我在使用中也发现^&*()这几个里面有一个也不能用作密码，忘了是&还是()
