### ISSUE TITLE
能否添加或者修改现有版本，让ss-bash和ssserver独立开来？

### ISSUE THREAD

**Issue by elfive** [hellofwy/ss-bash#32]
现有的版本是通过ssadmin.sh维护ssserver配置文件的，但是我需要用自己的ssserver配置文件，否则其他依赖ssserver的程序没法运行。

建议将ssserver配置文件的维护工作还给ssserver，ss-bash只需要做好限制某些端口流量的工作就好，独立起来开发也更好维护，我们使用起来也更加有条理。

**Comment by hellofwy** [comment]
之前有考虑过，不过我个人没有强烈需求就没写。
而且脚本对复杂功能实现起来也不太方便。
如果之后我有新的需求可能会用python来写。
现在这个脚本就不改了。

**Comment by elfive** [comment]
好吧，另外我帮你改正了重置用户流量的错误，新增加了一些操作结果输出提示，提交了个pull request，请您稍微注意一下吧。
