### ISSUE TITLE
想问一下，用户流量使用量置零这句正确调用格式？

### ISSUE THREAD

**Issue by Sunnysunny321** [hellofwy/ss-bash#37]
用户流量使用量置零
ssadmin.sh rused limit
rused和limit分别代表什么意思呢？

另外删除用户后，再显示当前用户流量信息时，该用户仍然存在?且删除语句运行后，必须使用ctrl+c才能停止，否则一直在等待~~
希望各位能给予指导？谢谢~~

**Comment by Sunnysunny321** [comment]
参考其他issue，已解决~~
正确形式为 ssadmin.sh rused port ，清除特定端口流量
另外，要确保bc 及 awk均安装，现在都能正常运行了，ubuntu/debian上测试

**Comment by PM100Fun** [comment]
dalao，我的ssadmin.sh rused port，不能重置sstraffic流量记录，如何是好？
