### ISSUE TITLE
如何重置流量统计？

### ISSUE THREAD

**Issue by cielpy** [hellofwy/ss-bash#4]

**Comment by hellofwy** [comment]
行署？什么意思？
看使用说明吧，https://github.com/hellofwy/ss-bash/wiki

**Comment by cielpy** [comment]
不好意思，打错了忘了检查，就是我的VPS流量每月初清零，但是脚本统计流量的累积的，没找到设置重置流量统计的选项。

**Comment by hellofwy** [comment]
帮助里有重置选项
reset_all_used，可以重置全部流量记录
还有重置单个端口的，你可以找找
目前不是自动重置的，得自己运行相关命令

**Comment by cielpy** [comment]
好的，谢谢。

**Comment by aounnbe** [comment]
您好，例如我想将50000端口的使用量置零，但是我不是太能看懂您的 ssadmin.sh rused limit 代码，我是应该在 putty 上输入 sudo ss-bash/ssadmin.sh rused 50000 吗?还是怎样呢? 望回复。

**Comment by hellofwy** [comment]
@aounnbe 是的。帮助里写错了，应该是ssadmin.sh rused port，一直没改。

**Comment by aounnbe** [comment]
明白了，谢谢帮助。

**Comment by aounnbe** [comment]
你好，我在 putty 中输入 sudo ss-bash/ssadmin.sh rused 50000 然后回车，却没有任何反应。系统是Debian 8，能否指点一下呢?

**Comment by hellofwy** [comment]
@aounnbe 我这里rused命令可以正常使用。根据你现在的描述我无法判断是软件本身问题还是你的使用方式问题。现在关于rused命令我知道的问题是 #2 ，不过一直没解决。

**Comment by aounnbe** [comment]
我是按照您的方法进行设置的，安装了bc，但是没有安装awk。其他各种操作命令都是正常的，就是使用量置零代码键入之后，VPS无任何反应，且流量统计失效了。顺带询问流量统计能恢复吗？

发送自 Outlook Mobile




On Sat, Feb 6, 2016 at 1:57 AM -0800, "hellofwy" <notifications@github.com> wrote:





@aounnbe 我这里rused命令可以正常使用。根据你现在的描述我无法判断是软件本身问题还是你的使用方式问题。现在关于rused命令我知道的问题是 #2 ，不过一直没解决。

---

**Comment by aounnbe** [comment]
我是按照你的方法进行设置的，安装了bc，但是没有安装awk。其他各种操作命令都是正常的，就是使用量置零代码键入之后，VPS无任何反应，且流量统计失效了。顺带询问流量统计能恢复吗？

**Comment by hellofwy** [comment]
@aounnbe 把软件删除，重新下载吧。

**Comment by aounnbe** [comment]
您好，我删除软件并重新安装bc和awk，已经可以完美使用。可能是我看到「KB GB计算问题和流量统计问题」这个问题中您回复他人说需要安装bc，而没有看到「请问为什么那个流量统计无效？」这个问题您回复所说需要安装bc和awk。所以应该是awk的缺失导致使用量置零导致流量统计失效。目前我已经可以使用 ssadmin.sh rused port 来将使用量置零。Anyway多谢您的帮助，新年快乐~
