### ISSUE TITLE
关于日志输出

### ISSUE THREAD

**Issue by Verinda** [hellofwy/ss-bash#6]
您好，请问使用这个流量统计脚本后，原先输出到 /var/log/shadowsocks.log 的日志不再输出了，有办法让 shadowsocks 继续输出日志吗？谢谢～

**Comment by hellofwy** [comment]
我也没注意原来的日志功能是怎么用的。
估计找到脚本里启动shadowsocks的命令，添加输出详情的参数，然后把输出重定向到日志文件就可以了吧，得你自己改了。

**Comment by xuexingmali** [comment]
@hellofwy 你好。请问下日志输出的问题。
我先是在ssadmin.sh中把启动命令改成$SSSERVER -c $JSON_FILE >/ss/ss.log & ,按我的理解 这样会把输出定向到ss.log.但实际上只是生成了ss.log但内容是空的，且输出信息仍然显示到标准输出上。因不太了解linux,所以尝试用ssserver自带的输出命令。$SSSERVER -c $JSON_FILE -d start --log-file /ss/ss.log 2>/dev/null >/dev/null & ,--log-file必须在-d模式时使用，此时可以正常启动ss,也把日志输出到ss.log了，但是ssadmin.sh检测不到ss是否启动，虽然有ssserver这个进程，但实际pid和/tmp/ssserver.pid里记录的不一样。请教下,Thx.

**Comment by hellofwy** [comment]
把命令改成：$SSSERVER -c $JSON_FILE -d start --log-file /ss/ss.log --pid-file $SSSERVER_PID 2>/dev/null >/dev/null & 

然后删除这句后面：
echo $! > $SSSERVER_PID

这样试试看。

**Comment by xuexingmali** [comment]
@hellofwy
已解决，十分感谢。

**Comment by KwToPA** [comment]
您好，
请问是这样改吗？
```
run_ssserver () {
    $SSSERVER -qq -c $JSON_FILE 2>/dev/null >/dev/null &
    echo $! > $SSSERVER_PID
}
```
改成
```
run_ssserver () {
    $SSSERVER -c $JSON_FILE -d start --log-file /ss/ss.log --pid-file $SSSERVER_PID 2>/dev/null >/dev/null &
    echo $! > $SSSERVER_PID
}
```
谢谢

**Comment by xuexingmali** [comment]
echo $! > $SSSERVER_PID注释掉

**Comment by KwToPA** [comment]
谢谢  解决问题了
