### ISSUE TITLE
KB GB计算问题和流量统计问题

### ISSUE THREAD

**Issue by shanlinfeiniao** [hellofwy/ss-bash#8]
您好，我遇到了两个小问题。 目前系统是Debian 7，vps为DigitalOcean的。安装时为重装系统后pip安装的shadowsocks

第一个问题：新建用户时使用 sudo ss-bash/ssadmin.sh add 8388 passwd 10G  时报错，报错位置在ssadmin.sh的第195行，内容为./ssadmin.sh: line 195: bc: command not found   
       我大概理解那一行是把流量单位换算成字节，比如1kb = 1024字节这种。执行后新端口出现在ssusers里，但流量那里是空白。。可以通过编辑ssusers修改流量。。在ssadmin.sh 里面搜索bc只找到这一处用到的情况。。查看那个旧版本也是类似的情况、
       我试着谷歌了一下看有没有类似的脚本用到这种单位转换，但是并没有找到。。我对shell不是很熟。。目前就会一点Python。。毕竟专业差的有点多。。

第二个问题比较麻烦，脚本正常运行，通过脚本添加的端口可以正常使用（手动ssusers修改流量）。但是没有监控流量。在traffic.log中已用流量为0，只有ssadmin.sh show一样没有。修改统计时间间隔为15s也不行。   如果重置用户流量 （使用ssadmin.sh reset_all_limit）之后重启ss-bash，所有端口无法使用。因此怀疑是监控流量没有正常运行。。执行iptables是正常。

谷歌发现有人有类似的问题，提在https://www.v2ex.com/t/221247  但是他似乎又解决了。。

主要是第二个问题，没办法统计流量有点麻烦。。现在只能用iftop凑合。。。希望解决一下。如果需要的话可以发给你vps的登录密码，在上面进行尝试。多谢啦

**Comment by hellofwy** [comment]
安装下bc这个软件就好了应该:
apt-get install bc

**Comment by shanlinfeiniao** [comment]
安装bc之后解决了第一个问题。。我本以为bc是一个变量，没想到居然是个软件。。还是我太菜了，侧面说明声明变量名称时要起个好名字啊。

但是流量统计那里依然为零。更悲催的是没有报错。我尝试重装系统后，只pip安装了ss、bc和这个脚本，但是统计流量数据仍然为零。。所以不知道该怎么描述这个问题。不知道您有没有思路，我尝试一下试试看。。

**Comment by hellofwy** [comment]
执行下面命令看看相应的iptables规则添加成功没.
sudo ss-bash/ssadmin.sh lrules
流量监控不是实时更新的,默认的统计间隔是5分钟, 第一次运行的时候可能10分钟后才有更新.

**Comment by shanlinfeiniao** [comment]
原来是我的错。。。不留心重装了n次用的还是Cent OS 掩面逃跑。。。脚本在Debian 7下完美运行。。。

**Comment by shanlinfeiniao** [comment]
实在是打扰您了。。。多谢帮助！

**Comment by athen1003** [comment]
请问作者centeros下怎么用，监控不到流量，其他都正常

**Comment by hellofwy** [comment]
@athen1003 到其他人 [fork](https://github.com/hellofwy/ss-bash/network) 的分支中找找是否有你需要的。
